import Head from "next/head";
import Navigation from "../components/Navbar/Navigation";
import Werdegang from "../components/Werdegang";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div className="bg-gray-800 min-h-screen h-full relative">
      <Head>
        <title>Persönliche Seite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative z-10">
        <header className="h-20 top-0 z-50">
          <Navigation />
        </header>

        <main className="text-5xl p-4 mx-auto max-w-7xl h-fit relative z-10 text-center">
          <h2 id="Werdegang" className="py-5">
            Werdegang
          </h2>
          <Werdegang />
          <h2 id="Skills" className="py-5">
            Skills
          </h2>
          <Skills />
        </main>

        <footer></footer>
      </div>
    </div>
  );
}
