import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/Navbar/Navigation";

export default function Home() {
  return (
    <div className="bg-gray-800 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navigation />
      </header>

      <main></main>

      <footer></footer>
    </div>
  );
}
